name: 'Lint Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black  # Install Flake8 and Black

    - name: Run Black (autoformatter)
      run: |
        black .  # Run Black to automatically format Python files

    - name: Run Linter
      run: |
        flake8 .  # Run Flake8 to lint Python files
        echo "Linted all the python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Install ESLint
      run: npm install eslint --global
    - name: Run ESLint with --fix option
      run: |
        eslint . --fix  # Run ESLint with --fix to automatically fix JavaScript linting errors
        echo "Linted all the JavaScript files successfully"
